<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS0618;CS1591;CS1572;CA1822</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Morph\Morph.csproj" />
    <ProjectReference Include="..\..\..\Sparkle.Net\PDFSparkle.csproj" />
  </ItemGroup>

</Project>
