<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CS0618;CS1591;CS1572</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="EmbeddedFonts\*.ttf" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="StaticSettingTests, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="Morph.Skia, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="Morph.Pdf, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="Morph.ImageSharp, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="Benchmarks, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <InternalsVisibleTo Include="Morph.PDFSparkle, PublicKey=002400000480000094000000060200000024000052534131000400000100010005AA7D6703369C6701F8527FC7536EE1F43584266AA043F7B5F58E6BF0CC55BEAD30F5D2F06DEBED488B221DBFA987C08B8178960C10E06002AB1ADC7D89AE62B78E6794ED60BA0561022EA6593F4AB3F1F1523826CBE43B6B6039B4B15291B3B83943E3A8FC1E7E35FFA862E82429410920B20B51128A53E3FB502065D56EB3" />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="SponsorCheck" PrivateAssets="all" Condition="'$(MORPH_TEST_CONTAINER)' != '1'" />
  </ItemGroup>

</Project>
